-- MySQL Script generated by MySQL Workbench
-- Sat May 11 11:04:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AnketaDB-IS221
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AnketaDB-IS221` ;

-- -----------------------------------------------------
-- Schema AnketaDB-IS221
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AnketaDB-IS221` DEFAULT CHARACTER SET utf8 ;
USE `AnketaDB-IS221` ;

-- -----------------------------------------------------
-- Table `AnketaDB-IS221`.`Polls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AnketaDB-IS221`.`Polls` ;

CREATE TABLE IF NOT EXISTS `AnketaDB-IS221`.`Polls` (
  `p_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`p_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnketaDB-IS221`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AnketaDB-IS221`.`Questions` ;

CREATE TABLE IF NOT EXISTS `AnketaDB-IS221`.`Questions` (
  `q_id` INT NOT NULL AUTO_INCREMENT,
  `p_id` INT NULL,
  `name` VARCHAR(200) NULL,
  `short_name` VARCHAR(50) NULL,
  PRIMARY KEY (`q_id`),
  INDEX `pools_key_idx` (`p_id` ASC),
  CONSTRAINT `pools_key`
    FOREIGN KEY (`p_id`)
    REFERENCES `AnketaDB-IS221`.`Polls` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnketaDB-IS221`.`Options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AnketaDB-IS221`.`Options` ;

CREATE TABLE IF NOT EXISTS `AnketaDB-IS221`.`Options` (
  `o_id` INT NOT NULL AUTO_INCREMENT,
  `q_id` INT NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`o_id`),
  INDEX `quest_opt_key_idx` (`q_id` ASC),
  CONSTRAINT `quest_opt_key`
    FOREIGN KEY (`q_id`)
    REFERENCES `AnketaDB-IS221`.`Questions` (`q_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnketaDB-IS221`.`Answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AnketaDB-IS221`.`Answers` ;

CREATE TABLE IF NOT EXISTS `AnketaDB-IS221`.`Answers` (
  `a_id` INT NOT NULL AUTO_INCREMENT,
  `q_id` INT NULL,
  `n_student` INT NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`a_id`),
  INDEX `answer_quest_key_idx` (`q_id` ASC),
  CONSTRAINT `answer_quest_key`
    FOREIGN KEY (`q_id`)
    REFERENCES `AnketaDB-IS221`.`Questions` (`q_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
